// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/autorix/themis/v1/themis.proto

package themisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Policy represents a business rule owned by a specific Tenant.
// The expression field contains a Google CEL expression that evaluates
// against a dynamic JSON payload provided at evaluation time.
type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Expression    string                 `protobuf:"bytes,5,opt,name=expression,proto3" json:"expression,omitempty"` // CEL expression, e.g. "amount < budget && status == 'active'"
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`    // Lower number = higher priority
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Arbitrary key-value metadata for filtering
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Policy) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *Policy) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Policy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Policy) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Policy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Policy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Expression    string                 `protobuf:"bytes,4,opt,name=expression,proto3" json:"expression,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePolicyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreatePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePolicyRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *CreatePolicyRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreatePolicyRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *CreatePolicyRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CreatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyResponse) Reset() {
	*x = CreatePolicyResponse{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyResponse) ProtoMessage() {}

func (x *CreatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyResponse.ProtoReflect.Descriptor instead.
func (*CreatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{3}
}

func (x *GetPolicyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetPolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type GetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{4}
}

func (x *GetPolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EnabledOnly   bool                   `protobuf:"varint,2,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`                                                                          // Filter: return only enabled policies
	LabelFilter   map[string]string      `protobuf:"bytes,3,rep,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Filter: match all specified labels
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{5}
}

func (x *ListPoliciesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListPoliciesRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

func (x *ListPoliciesRequest) GetLabelFilter() map[string]string {
	if x != nil {
		return x.LabelFilter
	}
	return nil
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*Policy              `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{6}
}

func (x *ListPoliciesResponse) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type UpdatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Expression    string                 `protobuf:"bytes,5,opt,name=expression,proto3" json:"expression,omitempty"`
	Priority      int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Enabled       bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyRequest) Reset() {
	*x = UpdatePolicyRequest{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyRequest) ProtoMessage() {}

func (x *UpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePolicyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdatePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *UpdatePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePolicyRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePolicyRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *UpdatePolicyRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdatePolicyRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpdatePolicyRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type UpdatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyResponse) Reset() {
	*x = UpdatePolicyResponse{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyResponse) ProtoMessage() {}

func (x *UpdatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyResponse.ProtoReflect.Descriptor instead.
func (*UpdatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type DeletePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PolicyId      string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePolicyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeletePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type DeletePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyResponse) Reset() {
	*x = DeletePolicyResponse{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyResponse) ProtoMessage() {}

func (x *DeletePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyResponse.ProtoReflect.Descriptor instead.
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{10}
}

// EvaluatePolicyRequest evaluates a single policy by ID or all matching
// policies for a tenant against the provided payload.
type EvaluatePolicyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Evaluate a single policy by ID. If empty, evaluates ALL enabled
	// policies for the tenant (optionally filtered by labels).
	PolicyId string `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// The transactional payload to evaluate against (e.g. {"amount": 5000, "status": "active"})
	Payload *structpb.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional label filter when evaluating multiple policies
	LabelFilter   map[string]string `protobuf:"bytes,4,rep,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatePolicyRequest) Reset() {
	*x = EvaluatePolicyRequest{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePolicyRequest) ProtoMessage() {}

func (x *EvaluatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePolicyRequest.ProtoReflect.Descriptor instead.
func (*EvaluatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{11}
}

func (x *EvaluatePolicyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EvaluatePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *EvaluatePolicyRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EvaluatePolicyRequest) GetLabelFilter() map[string]string {
	if x != nil {
		return x.LabelFilter
	}
	return nil
}

type PolicyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyName    string                 `protobuf:"bytes,2,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	Passed        bool                   `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`        // true if the CEL expression evaluated to true
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`           // Non-empty if evaluation failed (type error, etc.)
	Expression    string                 `protobuf:"bytes,5,opt,name=expression,proto3" json:"expression,omitempty"` // The evaluated expression (for audit trail)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyResult) Reset() {
	*x = PolicyResult{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyResult) ProtoMessage() {}

func (x *PolicyResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyResult.ProtoReflect.Descriptor instead.
func (*PolicyResult) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{12}
}

func (x *PolicyResult) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyResult) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *PolicyResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *PolicyResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PolicyResult) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

type EvaluatePolicyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AllPassed      bool                   `protobuf:"varint,1,opt,name=all_passed,json=allPassed,proto3" json:"all_passed,omitempty"` // true only if ALL evaluated policies passed
	Results        []*PolicyResult        `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`                       // Individual result per policy
	TotalEvaluated int32                  `protobuf:"varint,3,opt,name=total_evaluated,json=totalEvaluated,proto3" json:"total_evaluated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluatePolicyResponse) Reset() {
	*x = EvaluatePolicyResponse{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePolicyResponse) ProtoMessage() {}

func (x *EvaluatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePolicyResponse.ProtoReflect.Descriptor instead.
func (*EvaluatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{13}
}

func (x *EvaluatePolicyResponse) GetAllPassed() bool {
	if x != nil {
		return x.AllPassed
	}
	return false
}

func (x *EvaluatePolicyResponse) GetResults() []*PolicyResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *EvaluatePolicyResponse) GetTotalEvaluated() int32 {
	if x != nil {
		return x.TotalEvaluated
	}
	return 0
}

// BatchEvaluateRequest evaluates the same set of policies against
// multiple payloads in a single round-trip.
type BatchEvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LabelFilter   map[string]string      `protobuf:"bytes,2,rep,name=label_filter,json=labelFilter,proto3" json:"label_filter,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Payloads      []*structpb.Struct     `protobuf:"bytes,3,rep,name=payloads,proto3" json:"payloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEvaluateRequest) Reset() {
	*x = BatchEvaluateRequest{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEvaluateRequest) ProtoMessage() {}

func (x *BatchEvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEvaluateRequest.ProtoReflect.Descriptor instead.
func (*BatchEvaluateRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{14}
}

func (x *BatchEvaluateRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchEvaluateRequest) GetLabelFilter() map[string]string {
	if x != nil {
		return x.LabelFilter
	}
	return nil
}

func (x *BatchEvaluateRequest) GetPayloads() []*structpb.Struct {
	if x != nil {
		return x.Payloads
	}
	return nil
}

type BatchEvaluateResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Evaluations   []*EvaluatePolicyResponse `protobuf:"bytes,1,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEvaluateResponse) Reset() {
	*x = BatchEvaluateResponse{}
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEvaluateResponse) ProtoMessage() {}

func (x *BatchEvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_themis_v1_themis_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEvaluateResponse.ProtoReflect.Descriptor instead.
func (*BatchEvaluateResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_themis_v1_themis_proto_rawDescGZIP(), []int{15}
}

func (x *BatchEvaluateResponse) GetEvaluations() []*EvaluatePolicyResponse {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

var File_api_autorix_themis_v1_themis_proto protoreflect.FileDescriptor

const file_api_autorix_themis_v1_themis_proto_rawDesc = "" +
	"\n" +
	"\"api/autorix/themis/v1/themis.proto\x12\x11autorix.themis.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x03\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"expression\x18\x05 \x01(\tR\n" +
	"expression\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12=\n" +
	"\x06labels\x18\b \x03(\v2%.autorix.themis.v1.Policy.LabelsEntryR\x06labels\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x02\n" +
	"\x13CreatePolicyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"expression\x18\x04 \x01(\tR\n" +
	"expression\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12J\n" +
	"\x06labels\x18\a \x03(\v22.autorix.themis.v1.CreatePolicyRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x14CreatePolicyResponse\x121\n" +
	"\x06policy\x18\x01 \x01(\v2\x19.autorix.themis.v1.PolicyR\x06policy\"L\n" +
	"\x10GetPolicyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\"F\n" +
	"\x11GetPolicyResponse\x121\n" +
	"\x06policy\x18\x01 \x01(\v2\x19.autorix.themis.v1.PolicyR\x06policy\"\xf1\x01\n" +
	"\x13ListPoliciesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fenabled_only\x18\x02 \x01(\bR\venabledOnly\x12Z\n" +
	"\flabel_filter\x18\x03 \x03(\v27.autorix.themis.v1.ListPoliciesRequest.LabelFilterEntryR\vlabelFilter\x1a>\n" +
	"\x10LabelFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x14ListPoliciesResponse\x125\n" +
	"\bpolicies\x18\x01 \x03(\v2\x19.autorix.themis.v1.PolicyR\bpolicies\"\xe2\x02\n" +
	"\x13UpdatePolicyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"expression\x18\x05 \x01(\tR\n" +
	"expression\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12J\n" +
	"\x06labels\x18\b \x03(\v22.autorix.themis.v1.UpdatePolicyRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x14UpdatePolicyResponse\x121\n" +
	"\x06policy\x18\x01 \x01(\v2\x19.autorix.themis.v1.PolicyR\x06policy\"O\n" +
	"\x13DeletePolicyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\"\x16\n" +
	"\x14DeletePolicyResponse\"\xa2\x02\n" +
	"\x15EvaluatePolicyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\\\n" +
	"\flabel_filter\x18\x04 \x03(\v29.autorix.themis.v1.EvaluatePolicyRequest.LabelFilterEntryR\vlabelFilter\x1a>\n" +
	"\x10LabelFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\fPolicyResult\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x1f\n" +
	"\vpolicy_name\x18\x02 \x01(\tR\n" +
	"policyName\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1e\n" +
	"\n" +
	"expression\x18\x05 \x01(\tR\n" +
	"expression\"\x9b\x01\n" +
	"\x16EvaluatePolicyResponse\x12\x1d\n" +
	"\n" +
	"all_passed\x18\x01 \x01(\bR\tallPassed\x129\n" +
	"\aresults\x18\x02 \x03(\v2\x1f.autorix.themis.v1.PolicyResultR\aresults\x12'\n" +
	"\x0ftotal_evaluated\x18\x03 \x01(\x05R\x0etotalEvaluated\"\x85\x02\n" +
	"\x14BatchEvaluateRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12[\n" +
	"\flabel_filter\x18\x02 \x03(\v28.autorix.themis.v1.BatchEvaluateRequest.LabelFilterEntryR\vlabelFilter\x123\n" +
	"\bpayloads\x18\x03 \x03(\v2\x17.google.protobuf.StructR\bpayloads\x1a>\n" +
	"\x10LabelFilterEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x15BatchEvaluateResponse\x12K\n" +
	"\vevaluations\x18\x01 \x03(\v2).autorix.themis.v1.EvaluatePolicyResponseR\vevaluations2\xb6\x05\n" +
	"\rThemisService\x12_\n" +
	"\fCreatePolicy\x12&.autorix.themis.v1.CreatePolicyRequest\x1a'.autorix.themis.v1.CreatePolicyResponse\x12V\n" +
	"\tGetPolicy\x12#.autorix.themis.v1.GetPolicyRequest\x1a$.autorix.themis.v1.GetPolicyResponse\x12_\n" +
	"\fListPolicies\x12&.autorix.themis.v1.ListPoliciesRequest\x1a'.autorix.themis.v1.ListPoliciesResponse\x12_\n" +
	"\fUpdatePolicy\x12&.autorix.themis.v1.UpdatePolicyRequest\x1a'.autorix.themis.v1.UpdatePolicyResponse\x12_\n" +
	"\fDeletePolicy\x12&.autorix.themis.v1.DeletePolicyRequest\x1a'.autorix.themis.v1.DeletePolicyResponse\x12e\n" +
	"\x0eEvaluatePolicy\x12(.autorix.themis.v1.EvaluatePolicyRequest\x1a).autorix.themis.v1.EvaluatePolicyResponse\x12b\n" +
	"\rBatchEvaluate\x12'.autorix.themis.v1.BatchEvaluateRequest\x1a(.autorix.themis.v1.BatchEvaluateResponseB:Z8github.com/autorix/themis/api/autorix/themis/v1;themisv1b\x06proto3"

var (
	file_api_autorix_themis_v1_themis_proto_rawDescOnce sync.Once
	file_api_autorix_themis_v1_themis_proto_rawDescData []byte
)

func file_api_autorix_themis_v1_themis_proto_rawDescGZIP() []byte {
	file_api_autorix_themis_v1_themis_proto_rawDescOnce.Do(func() {
		file_api_autorix_themis_v1_themis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_autorix_themis_v1_themis_proto_rawDesc), len(file_api_autorix_themis_v1_themis_proto_rawDesc)))
	})
	return file_api_autorix_themis_v1_themis_proto_rawDescData
}

var file_api_autorix_themis_v1_themis_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_autorix_themis_v1_themis_proto_goTypes = []any{
	(*Policy)(nil),                 // 0: autorix.themis.v1.Policy
	(*CreatePolicyRequest)(nil),    // 1: autorix.themis.v1.CreatePolicyRequest
	(*CreatePolicyResponse)(nil),   // 2: autorix.themis.v1.CreatePolicyResponse
	(*GetPolicyRequest)(nil),       // 3: autorix.themis.v1.GetPolicyRequest
	(*GetPolicyResponse)(nil),      // 4: autorix.themis.v1.GetPolicyResponse
	(*ListPoliciesRequest)(nil),    // 5: autorix.themis.v1.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),   // 6: autorix.themis.v1.ListPoliciesResponse
	(*UpdatePolicyRequest)(nil),    // 7: autorix.themis.v1.UpdatePolicyRequest
	(*UpdatePolicyResponse)(nil),   // 8: autorix.themis.v1.UpdatePolicyResponse
	(*DeletePolicyRequest)(nil),    // 9: autorix.themis.v1.DeletePolicyRequest
	(*DeletePolicyResponse)(nil),   // 10: autorix.themis.v1.DeletePolicyResponse
	(*EvaluatePolicyRequest)(nil),  // 11: autorix.themis.v1.EvaluatePolicyRequest
	(*PolicyResult)(nil),           // 12: autorix.themis.v1.PolicyResult
	(*EvaluatePolicyResponse)(nil), // 13: autorix.themis.v1.EvaluatePolicyResponse
	(*BatchEvaluateRequest)(nil),   // 14: autorix.themis.v1.BatchEvaluateRequest
	(*BatchEvaluateResponse)(nil),  // 15: autorix.themis.v1.BatchEvaluateResponse
	nil,                            // 16: autorix.themis.v1.Policy.LabelsEntry
	nil,                            // 17: autorix.themis.v1.CreatePolicyRequest.LabelsEntry
	nil,                            // 18: autorix.themis.v1.ListPoliciesRequest.LabelFilterEntry
	nil,                            // 19: autorix.themis.v1.UpdatePolicyRequest.LabelsEntry
	nil,                            // 20: autorix.themis.v1.EvaluatePolicyRequest.LabelFilterEntry
	nil,                            // 21: autorix.themis.v1.BatchEvaluateRequest.LabelFilterEntry
	(*timestamppb.Timestamp)(nil),  // 22: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 23: google.protobuf.Struct
}
var file_api_autorix_themis_v1_themis_proto_depIdxs = []int32{
	16, // 0: autorix.themis.v1.Policy.labels:type_name -> autorix.themis.v1.Policy.LabelsEntry
	22, // 1: autorix.themis.v1.Policy.created_at:type_name -> google.protobuf.Timestamp
	22, // 2: autorix.themis.v1.Policy.updated_at:type_name -> google.protobuf.Timestamp
	17, // 3: autorix.themis.v1.CreatePolicyRequest.labels:type_name -> autorix.themis.v1.CreatePolicyRequest.LabelsEntry
	0,  // 4: autorix.themis.v1.CreatePolicyResponse.policy:type_name -> autorix.themis.v1.Policy
	0,  // 5: autorix.themis.v1.GetPolicyResponse.policy:type_name -> autorix.themis.v1.Policy
	18, // 6: autorix.themis.v1.ListPoliciesRequest.label_filter:type_name -> autorix.themis.v1.ListPoliciesRequest.LabelFilterEntry
	0,  // 7: autorix.themis.v1.ListPoliciesResponse.policies:type_name -> autorix.themis.v1.Policy
	19, // 8: autorix.themis.v1.UpdatePolicyRequest.labels:type_name -> autorix.themis.v1.UpdatePolicyRequest.LabelsEntry
	0,  // 9: autorix.themis.v1.UpdatePolicyResponse.policy:type_name -> autorix.themis.v1.Policy
	23, // 10: autorix.themis.v1.EvaluatePolicyRequest.payload:type_name -> google.protobuf.Struct
	20, // 11: autorix.themis.v1.EvaluatePolicyRequest.label_filter:type_name -> autorix.themis.v1.EvaluatePolicyRequest.LabelFilterEntry
	12, // 12: autorix.themis.v1.EvaluatePolicyResponse.results:type_name -> autorix.themis.v1.PolicyResult
	21, // 13: autorix.themis.v1.BatchEvaluateRequest.label_filter:type_name -> autorix.themis.v1.BatchEvaluateRequest.LabelFilterEntry
	23, // 14: autorix.themis.v1.BatchEvaluateRequest.payloads:type_name -> google.protobuf.Struct
	13, // 15: autorix.themis.v1.BatchEvaluateResponse.evaluations:type_name -> autorix.themis.v1.EvaluatePolicyResponse
	1,  // 16: autorix.themis.v1.ThemisService.CreatePolicy:input_type -> autorix.themis.v1.CreatePolicyRequest
	3,  // 17: autorix.themis.v1.ThemisService.GetPolicy:input_type -> autorix.themis.v1.GetPolicyRequest
	5,  // 18: autorix.themis.v1.ThemisService.ListPolicies:input_type -> autorix.themis.v1.ListPoliciesRequest
	7,  // 19: autorix.themis.v1.ThemisService.UpdatePolicy:input_type -> autorix.themis.v1.UpdatePolicyRequest
	9,  // 20: autorix.themis.v1.ThemisService.DeletePolicy:input_type -> autorix.themis.v1.DeletePolicyRequest
	11, // 21: autorix.themis.v1.ThemisService.EvaluatePolicy:input_type -> autorix.themis.v1.EvaluatePolicyRequest
	14, // 22: autorix.themis.v1.ThemisService.BatchEvaluate:input_type -> autorix.themis.v1.BatchEvaluateRequest
	2,  // 23: autorix.themis.v1.ThemisService.CreatePolicy:output_type -> autorix.themis.v1.CreatePolicyResponse
	4,  // 24: autorix.themis.v1.ThemisService.GetPolicy:output_type -> autorix.themis.v1.GetPolicyResponse
	6,  // 25: autorix.themis.v1.ThemisService.ListPolicies:output_type -> autorix.themis.v1.ListPoliciesResponse
	8,  // 26: autorix.themis.v1.ThemisService.UpdatePolicy:output_type -> autorix.themis.v1.UpdatePolicyResponse
	10, // 27: autorix.themis.v1.ThemisService.DeletePolicy:output_type -> autorix.themis.v1.DeletePolicyResponse
	13, // 28: autorix.themis.v1.ThemisService.EvaluatePolicy:output_type -> autorix.themis.v1.EvaluatePolicyResponse
	15, // 29: autorix.themis.v1.ThemisService.BatchEvaluate:output_type -> autorix.themis.v1.BatchEvaluateResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_autorix_themis_v1_themis_proto_init() }
func file_api_autorix_themis_v1_themis_proto_init() {
	if File_api_autorix_themis_v1_themis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_autorix_themis_v1_themis_proto_rawDesc), len(file_api_autorix_themis_v1_themis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_autorix_themis_v1_themis_proto_goTypes,
		DependencyIndexes: file_api_autorix_themis_v1_themis_proto_depIdxs,
		MessageInfos:      file_api_autorix_themis_v1_themis_proto_msgTypes,
	}.Build()
	File_api_autorix_themis_v1_themis_proto = out.File
	file_api_autorix_themis_v1_themis_proto_goTypes = nil
	file_api_autorix_themis_v1_themis_proto_depIdxs = nil
}
