// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/autorix/argus/v1/argus.proto

package argusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Endpoints an instance advertises to the registry, so Argus (and later
// the console/CLI/Terraform provider) can address it without hardcoded
// per-environment configuration.
type Endpoints struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestUrl       string                 `protobuf:"bytes,1,opt,name=rest_url,json=restUrl,proto3" json:"rest_url,omitempty"`
	GrpcUrl       string                 `protobuf:"bytes,2,opt,name=grpc_url,json=grpcUrl,proto3" json:"grpc_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoints) Reset() {
	*x = Endpoints{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoints) ProtoMessage() {}

func (x *Endpoints) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoints.ProtoReflect.Descriptor instead.
func (*Endpoints) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{0}
}

func (x *Endpoints) GetRestUrl() string {
	if x != nil {
		return x.RestUrl
	}
	return ""
}

func (x *Endpoints) GetGrpcUrl() string {
	if x != nil {
		return x.GrpcUrl
	}
	return ""
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One-time-use enrollment token minted via the REST admin API
	// (POST /v1/enrollment-tokens). Consumed on success.
	EnrollmentToken string `protobuf:"bytes,1,opt,name=enrollment_token,json=enrollmentToken,proto3" json:"enrollment_token,omitempty"`
	EngineType      string `protobuf:"bytes,2,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	// Stable across restarts — derived from hostname when the engine has
	// none configured. Used with engine_type + environment as the upsert
	// key, so a restarting engine updates its row instead of accumulating
	// duplicates.
	InstanceId    string     `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Environment   string     `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	Version       string     `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	BuildSha      string     `protobuf:"bytes,6,opt,name=build_sha,json=buildSha,proto3" json:"build_sha,omitempty"`
	SchemaVersion string     `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Capabilities  []string   `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Endpoints     *Endpoints `protobuf:"bytes,9,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetEnrollmentToken() string {
	if x != nil {
		return x.EnrollmentToken
	}
	return ""
}

func (x *RegisterRequest) GetEngineType() string {
	if x != nil {
		return x.EngineType
	}
	return ""
}

func (x *RegisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetBuildSha() string {
	if x != nil {
		return x.BuildSha
	}
	return ""
}

func (x *RegisterRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetEndpoints() *Endpoints {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type RegisterResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InstanceUuid string                 `protobuf:"bytes,1,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"`
	// Long-lived, rotatable per-instance secret replacing the one-shot
	// enrollment token. Returned exactly once — Argus stores only its hash.
	InstanceCredential       string `protobuf:"bytes,2,opt,name=instance_credential,json=instanceCredential,proto3" json:"instance_credential,omitempty"`
	HeartbeatIntervalSeconds int32  `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetInstanceUuid() string {
	if x != nil {
		return x.InstanceUuid
	}
	return ""
}

func (x *RegisterResponse) GetInstanceCredential() string {
	if x != nil {
		return x.InstanceCredential
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type DependencyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Reachable     bool                   `protobuf:"varint,2,opt,name=reachable,proto3" json:"reachable,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyStatus) Reset() {
	*x = DependencyStatus{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyStatus) ProtoMessage() {}

func (x *DependencyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyStatus.ProtoReflect.Descriptor instead.
func (*DependencyStatus) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{3}
}

func (x *DependencyStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependencyStatus) GetReachable() bool {
	if x != nil {
		return x.Reachable
	}
	return false
}

func (x *DependencyStatus) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type HeartbeatRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InstanceUuid string                 `protobuf:"bytes,1,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"`
	Live         bool                   `protobuf:"varint,2,opt,name=live,proto3" json:"live,omitempty"`
	Ready        bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	Dependencies []*DependencyStatus    `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	Counters     *structpb.Struct       `protobuf:"bytes,5,opt,name=counters,proto3" json:"counters,omitempty"`
	// timestamp_unix + nonce + signature: HMAC(instance_credential, body)
	// over the rest of the message, so a captured heartbeat cannot be
	// replayed to keep a dead instance looking alive.
	TimestampUnix int64  `protobuf:"varint,6,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Nonce         string `protobuf:"bytes,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature     string `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetInstanceUuid() string {
	if x != nil {
		return x.InstanceUuid
	}
	return ""
}

func (x *HeartbeatRequest) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

func (x *HeartbeatRequest) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HeartbeatRequest) GetDependencies() []*DependencyStatus {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *HeartbeatRequest) GetCounters() *structpb.Struct {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *HeartbeatRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *HeartbeatRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy | degraded | unreachable — Argus's own view, which may lag
	// the engine's self-reported live/ready by up to one evaluator sweep.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeregisterRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InstanceUuid string                 `protobuf:"bytes,1,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"`
	// Freeform, e.g. "sigterm", "operator requested" — what separates a
	// graceful stop from an incident in the fleet timeline.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{6}
}

func (x *DeregisterRequest) GetInstanceUuid() string {
	if x != nil {
		return x.InstanceUuid
	}
	return ""
}

func (x *DeregisterRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{7}
}

type RotateCredentialRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstanceUuid      string                 `protobuf:"bytes,1,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"`
	CurrentCredential string                 `protobuf:"bytes,2,opt,name=current_credential,json=currentCredential,proto3" json:"current_credential,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RotateCredentialRequest) Reset() {
	*x = RotateCredentialRequest{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCredentialRequest) ProtoMessage() {}

func (x *RotateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCredentialRequest.ProtoReflect.Descriptor instead.
func (*RotateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{8}
}

func (x *RotateCredentialRequest) GetInstanceUuid() string {
	if x != nil {
		return x.InstanceUuid
	}
	return ""
}

func (x *RotateCredentialRequest) GetCurrentCredential() string {
	if x != nil {
		return x.CurrentCredential
	}
	return ""
}

type RotateCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewCredential string                 `protobuf:"bytes,1,opt,name=new_credential,json=newCredential,proto3" json:"new_credential,omitempty"`
	// current_credential keeps working until this instant, so rotation is
	// not a hard cutover.
	OverlapUntil  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=overlap_until,json=overlapUntil,proto3" json:"overlap_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateCredentialResponse) Reset() {
	*x = RotateCredentialResponse{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateCredentialResponse) ProtoMessage() {}

func (x *RotateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateCredentialResponse.ProtoReflect.Descriptor instead.
func (*RotateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{9}
}

func (x *RotateCredentialResponse) GetNewCredential() string {
	if x != nil {
		return x.NewCredential
	}
	return ""
}

func (x *RotateCredentialResponse) GetOverlapUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.OverlapUntil
	}
	return nil
}

type Instance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EngineType      string                 `protobuf:"bytes,2,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	InstanceId      string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Environment     string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	Version         string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	BuildSha        string                 `protobuf:"bytes,6,opt,name=build_sha,json=buildSha,proto3" json:"build_sha,omitempty"`
	SchemaVersion   string                 `protobuf:"bytes,7,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Endpoints       *Endpoints             `protobuf:"bytes,9,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	FirstSeenAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=first_seen_at,json=firstSeenAt,proto3" json:"first_seen_at,omitempty"`
	LastHeartbeatAt *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{10}
}

func (x *Instance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instance) GetEngineType() string {
	if x != nil {
		return x.EngineType
	}
	return ""
}

func (x *Instance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Instance) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *Instance) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Instance) GetBuildSha() string {
	if x != nil {
		return x.BuildSha
	}
	return ""
}

func (x *Instance) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

func (x *Instance) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Instance) GetEndpoints() *Endpoints {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *Instance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Instance) GetFirstSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeenAt
	}
	return nil
}

func (x *Instance) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

type GetInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceUuid  string                 `protobuf:"bytes,1,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceRequest) Reset() {
	*x = GetInstanceRequest{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceRequest) ProtoMessage() {}

func (x *GetInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{11}
}

func (x *GetInstanceRequest) GetInstanceUuid() string {
	if x != nil {
		return x.InstanceUuid
	}
	return ""
}

// InstanceEvent is one entry of an instance's append-only fleet timeline
// (registered, degraded, unreachable, evicted, deregistered, ...).
type InstanceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Detail        *structpb.Struct       `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceEvent) Reset() {
	*x = InstanceEvent{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceEvent) ProtoMessage() {}

func (x *InstanceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceEvent.ProtoReflect.Descriptor instead.
func (*InstanceEvent) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{12}
}

func (x *InstanceEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InstanceEvent) GetDetail() *structpb.Struct {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *InstanceEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// InstanceDependencyEdge is one declared or observed dependency of an
// instance on another engine_type — the raw edge GetInstance returns inline,
// so a caller does not have to fan out to a separate topology call just to
// render one instance's dependencies.
type InstanceDependencyEdge struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	DependsOnEngineType string                 `protobuf:"bytes,1,opt,name=depends_on_engine_type,json=dependsOnEngineType,proto3" json:"depends_on_engine_type,omitempty"`
	Declared            bool                   `protobuf:"varint,2,opt,name=declared,proto3" json:"declared,omitempty"`
	LastProbeReachable  bool                   `protobuf:"varint,3,opt,name=last_probe_reachable,json=lastProbeReachable,proto3" json:"last_probe_reachable,omitempty"`
	LastProbeLatencyMs  float64                `protobuf:"fixed64,4,opt,name=last_probe_latency_ms,json=lastProbeLatencyMs,proto3" json:"last_probe_latency_ms,omitempty"`
	LastProbedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_probed_at,json=lastProbedAt,proto3" json:"last_probed_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InstanceDependencyEdge) Reset() {
	*x = InstanceDependencyEdge{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceDependencyEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceDependencyEdge) ProtoMessage() {}

func (x *InstanceDependencyEdge) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceDependencyEdge.ProtoReflect.Descriptor instead.
func (*InstanceDependencyEdge) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{13}
}

func (x *InstanceDependencyEdge) GetDependsOnEngineType() string {
	if x != nil {
		return x.DependsOnEngineType
	}
	return ""
}

func (x *InstanceDependencyEdge) GetDeclared() bool {
	if x != nil {
		return x.Declared
	}
	return false
}

func (x *InstanceDependencyEdge) GetLastProbeReachable() bool {
	if x != nil {
		return x.LastProbeReachable
	}
	return false
}

func (x *InstanceDependencyEdge) GetLastProbeLatencyMs() float64 {
	if x != nil {
		return x.LastProbeLatencyMs
	}
	return 0
}

func (x *InstanceDependencyEdge) GetLastProbedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastProbedAt
	}
	return nil
}

type GetInstanceResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Instance *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Most recent timeline events for this instance, newest first.
	Events []*InstanceEvent `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// Declared/observed dependency edges for this instance.
	Dependencies  []*InstanceDependencyEdge `protobuf:"bytes,3,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceResponse) Reset() {
	*x = GetInstanceResponse{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceResponse) ProtoMessage() {}

func (x *GetInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetInstanceResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{14}
}

func (x *GetInstanceResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

func (x *GetInstanceResponse) GetEvents() []*InstanceEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *GetInstanceResponse) GetDependencies() []*InstanceDependencyEdge {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type ListInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	EngineType    string                 `protobuf:"bytes,2,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{15}
}

func (x *ListInstancesRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ListInstancesRequest) GetEngineType() string {
	if x != nil {
		return x.EngineType
	}
	return ""
}

func (x *ListInstancesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListInstancesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListInstancesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*Instance            `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_argus_v1_argus_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_argus_v1_argus_proto_rawDescGZIP(), []int{16}
}

func (x *ListInstancesResponse) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ListInstancesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListInstancesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_api_autorix_argus_v1_argus_proto protoreflect.FileDescriptor

const file_api_autorix_argus_v1_argus_proto_rawDesc = "" +
	"\n" +
	" api/autorix/argus/v1/argus.proto\x12\x10autorix.argus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"A\n" +
	"\tEndpoints\x12\x19\n" +
	"\brest_url\x18\x01 \x01(\tR\arestUrl\x12\x19\n" +
	"\bgrpc_url\x18\x02 \x01(\tR\agrpcUrl\"\xdd\x02\n" +
	"\x0fRegisterRequest\x12)\n" +
	"\x10enrollment_token\x18\x01 \x01(\tR\x0fenrollmentToken\x12\x1f\n" +
	"\vengine_type\x18\x02 \x01(\tR\n" +
	"engineType\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1b\n" +
	"\tbuild_sha\x18\x06 \x01(\tR\bbuildSha\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x12\"\n" +
	"\fcapabilities\x18\b \x03(\tR\fcapabilities\x129\n" +
	"\tendpoints\x18\t \x01(\v2\x1b.autorix.argus.v1.EndpointsR\tendpoints\"\xa6\x01\n" +
	"\x10RegisterResponse\x12#\n" +
	"\rinstance_uuid\x18\x01 \x01(\tR\finstanceUuid\x12/\n" +
	"\x13instance_credential\x18\x02 \x01(\tR\x12instanceCredential\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\"c\n" +
	"\x10DependencyStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\treachable\x18\x02 \x01(\bR\treachable\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x01R\tlatencyMs\"\xb9\x02\n" +
	"\x10HeartbeatRequest\x12#\n" +
	"\rinstance_uuid\x18\x01 \x01(\tR\finstanceUuid\x12\x12\n" +
	"\x04live\x18\x02 \x01(\bR\x04live\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12F\n" +
	"\fdependencies\x18\x04 \x03(\v2\".autorix.argus.v1.DependencyStatusR\fdependencies\x123\n" +
	"\bcounters\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bcounters\x12%\n" +
	"\x0etimestamp_unix\x18\x06 \x01(\x03R\rtimestampUnix\x12\x14\n" +
	"\x05nonce\x18\a \x01(\tR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\"+\n" +
	"\x11HeartbeatResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"P\n" +
	"\x11DeregisterRequest\x12#\n" +
	"\rinstance_uuid\x18\x01 \x01(\tR\finstanceUuid\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x14\n" +
	"\x12DeregisterResponse\"m\n" +
	"\x17RotateCredentialRequest\x12#\n" +
	"\rinstance_uuid\x18\x01 \x01(\tR\finstanceUuid\x12-\n" +
	"\x12current_credential\x18\x02 \x01(\tR\x11currentCredential\"\x82\x01\n" +
	"\x18RotateCredentialResponse\x12%\n" +
	"\x0enew_credential\x18\x01 \x01(\tR\rnewCredential\x12?\n" +
	"\roverlap_until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\foverlapUntil\"\xdb\x03\n" +
	"\bInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vengine_type\x18\x02 \x01(\tR\n" +
	"engineType\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x1b\n" +
	"\tbuild_sha\x18\x06 \x01(\tR\bbuildSha\x12%\n" +
	"\x0eschema_version\x18\a \x01(\tR\rschemaVersion\x12\"\n" +
	"\fcapabilities\x18\b \x03(\tR\fcapabilities\x129\n" +
	"\tendpoints\x18\t \x01(\v2\x1b.autorix.argus.v1.EndpointsR\tendpoints\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12>\n" +
	"\rfirst_seen_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vfirstSeenAt\x12F\n" +
	"\x11last_heartbeat_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\"9\n" +
	"\x12GetInstanceRequest\x12#\n" +
	"\rinstance_uuid\x18\x01 \x01(\tR\finstanceUuid\"\x91\x01\n" +
	"\rInstanceEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12/\n" +
	"\x06detail\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06detail\x12;\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\x90\x02\n" +
	"\x16InstanceDependencyEdge\x123\n" +
	"\x16depends_on_engine_type\x18\x01 \x01(\tR\x13dependsOnEngineType\x12\x1a\n" +
	"\bdeclared\x18\x02 \x01(\bR\bdeclared\x120\n" +
	"\x14last_probe_reachable\x18\x03 \x01(\bR\x12lastProbeReachable\x121\n" +
	"\x15last_probe_latency_ms\x18\x04 \x01(\x01R\x12lastProbeLatencyMs\x12@\n" +
	"\x0elast_probed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\flastProbedAt\"\xd4\x01\n" +
	"\x13GetInstanceResponse\x126\n" +
	"\binstance\x18\x01 \x01(\v2\x1a.autorix.argus.v1.InstanceR\binstance\x127\n" +
	"\x06events\x18\x02 \x03(\v2\x1f.autorix.argus.v1.InstanceEventR\x06events\x12L\n" +
	"\fdependencies\x18\x03 \x03(\v2(.autorix.argus.v1.InstanceDependencyEdgeR\fdependencies\"\x9f\x01\n" +
	"\x14ListInstancesRequest\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x12\x1f\n" +
	"\vengine_type\x18\x02 \x01(\tR\n" +
	"engineType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\x8d\x01\n" +
	"\x15ListInstancesResponse\x128\n" +
	"\tinstances\x18\x01 \x03(\v2\x1a.autorix.argus.v1.InstanceR\tinstances\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore2\xb9\x04\n" +
	"\fArgusService\x12Q\n" +
	"\bRegister\x12!.autorix.argus.v1.RegisterRequest\x1a\".autorix.argus.v1.RegisterResponse\x12T\n" +
	"\tHeartbeat\x12\".autorix.argus.v1.HeartbeatRequest\x1a#.autorix.argus.v1.HeartbeatResponse\x12W\n" +
	"\n" +
	"Deregister\x12#.autorix.argus.v1.DeregisterRequest\x1a$.autorix.argus.v1.DeregisterResponse\x12i\n" +
	"\x10RotateCredential\x12).autorix.argus.v1.RotateCredentialRequest\x1a*.autorix.argus.v1.RotateCredentialResponse\x12Z\n" +
	"\vGetInstance\x12$.autorix.argus.v1.GetInstanceRequest\x1a%.autorix.argus.v1.GetInstanceResponse\x12`\n" +
	"\rListInstances\x12&.autorix.argus.v1.ListInstancesRequest\x1a'.autorix.argus.v1.ListInstancesResponseB7Z5github.com/autorix/argus/api/autorix/argus/v1;argusv1b\x06proto3"

var (
	file_api_autorix_argus_v1_argus_proto_rawDescOnce sync.Once
	file_api_autorix_argus_v1_argus_proto_rawDescData []byte
)

func file_api_autorix_argus_v1_argus_proto_rawDescGZIP() []byte {
	file_api_autorix_argus_v1_argus_proto_rawDescOnce.Do(func() {
		file_api_autorix_argus_v1_argus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_autorix_argus_v1_argus_proto_rawDesc), len(file_api_autorix_argus_v1_argus_proto_rawDesc)))
	})
	return file_api_autorix_argus_v1_argus_proto_rawDescData
}

var file_api_autorix_argus_v1_argus_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_autorix_argus_v1_argus_proto_goTypes = []any{
	(*Endpoints)(nil),                // 0: autorix.argus.v1.Endpoints
	(*RegisterRequest)(nil),          // 1: autorix.argus.v1.RegisterRequest
	(*RegisterResponse)(nil),         // 2: autorix.argus.v1.RegisterResponse
	(*DependencyStatus)(nil),         // 3: autorix.argus.v1.DependencyStatus
	(*HeartbeatRequest)(nil),         // 4: autorix.argus.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 5: autorix.argus.v1.HeartbeatResponse
	(*DeregisterRequest)(nil),        // 6: autorix.argus.v1.DeregisterRequest
	(*DeregisterResponse)(nil),       // 7: autorix.argus.v1.DeregisterResponse
	(*RotateCredentialRequest)(nil),  // 8: autorix.argus.v1.RotateCredentialRequest
	(*RotateCredentialResponse)(nil), // 9: autorix.argus.v1.RotateCredentialResponse
	(*Instance)(nil),                 // 10: autorix.argus.v1.Instance
	(*GetInstanceRequest)(nil),       // 11: autorix.argus.v1.GetInstanceRequest
	(*InstanceEvent)(nil),            // 12: autorix.argus.v1.InstanceEvent
	(*InstanceDependencyEdge)(nil),   // 13: autorix.argus.v1.InstanceDependencyEdge
	(*GetInstanceResponse)(nil),      // 14: autorix.argus.v1.GetInstanceResponse
	(*ListInstancesRequest)(nil),     // 15: autorix.argus.v1.ListInstancesRequest
	(*ListInstancesResponse)(nil),    // 16: autorix.argus.v1.ListInstancesResponse
	(*structpb.Struct)(nil),          // 17: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),    // 18: google.protobuf.Timestamp
}
var file_api_autorix_argus_v1_argus_proto_depIdxs = []int32{
	0,  // 0: autorix.argus.v1.RegisterRequest.endpoints:type_name -> autorix.argus.v1.Endpoints
	3,  // 1: autorix.argus.v1.HeartbeatRequest.dependencies:type_name -> autorix.argus.v1.DependencyStatus
	17, // 2: autorix.argus.v1.HeartbeatRequest.counters:type_name -> google.protobuf.Struct
	18, // 3: autorix.argus.v1.RotateCredentialResponse.overlap_until:type_name -> google.protobuf.Timestamp
	0,  // 4: autorix.argus.v1.Instance.endpoints:type_name -> autorix.argus.v1.Endpoints
	18, // 5: autorix.argus.v1.Instance.first_seen_at:type_name -> google.protobuf.Timestamp
	18, // 6: autorix.argus.v1.Instance.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	17, // 7: autorix.argus.v1.InstanceEvent.detail:type_name -> google.protobuf.Struct
	18, // 8: autorix.argus.v1.InstanceEvent.occurred_at:type_name -> google.protobuf.Timestamp
	18, // 9: autorix.argus.v1.InstanceDependencyEdge.last_probed_at:type_name -> google.protobuf.Timestamp
	10, // 10: autorix.argus.v1.GetInstanceResponse.instance:type_name -> autorix.argus.v1.Instance
	12, // 11: autorix.argus.v1.GetInstanceResponse.events:type_name -> autorix.argus.v1.InstanceEvent
	13, // 12: autorix.argus.v1.GetInstanceResponse.dependencies:type_name -> autorix.argus.v1.InstanceDependencyEdge
	10, // 13: autorix.argus.v1.ListInstancesResponse.instances:type_name -> autorix.argus.v1.Instance
	1,  // 14: autorix.argus.v1.ArgusService.Register:input_type -> autorix.argus.v1.RegisterRequest
	4,  // 15: autorix.argus.v1.ArgusService.Heartbeat:input_type -> autorix.argus.v1.HeartbeatRequest
	6,  // 16: autorix.argus.v1.ArgusService.Deregister:input_type -> autorix.argus.v1.DeregisterRequest
	8,  // 17: autorix.argus.v1.ArgusService.RotateCredential:input_type -> autorix.argus.v1.RotateCredentialRequest
	11, // 18: autorix.argus.v1.ArgusService.GetInstance:input_type -> autorix.argus.v1.GetInstanceRequest
	15, // 19: autorix.argus.v1.ArgusService.ListInstances:input_type -> autorix.argus.v1.ListInstancesRequest
	2,  // 20: autorix.argus.v1.ArgusService.Register:output_type -> autorix.argus.v1.RegisterResponse
	5,  // 21: autorix.argus.v1.ArgusService.Heartbeat:output_type -> autorix.argus.v1.HeartbeatResponse
	7,  // 22: autorix.argus.v1.ArgusService.Deregister:output_type -> autorix.argus.v1.DeregisterResponse
	9,  // 23: autorix.argus.v1.ArgusService.RotateCredential:output_type -> autorix.argus.v1.RotateCredentialResponse
	14, // 24: autorix.argus.v1.ArgusService.GetInstance:output_type -> autorix.argus.v1.GetInstanceResponse
	16, // 25: autorix.argus.v1.ArgusService.ListInstances:output_type -> autorix.argus.v1.ListInstancesResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_autorix_argus_v1_argus_proto_init() }
func file_api_autorix_argus_v1_argus_proto_init() {
	if File_api_autorix_argus_v1_argus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_autorix_argus_v1_argus_proto_rawDesc), len(file_api_autorix_argus_v1_argus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_autorix_argus_v1_argus_proto_goTypes,
		DependencyIndexes: file_api_autorix_argus_v1_argus_proto_depIdxs,
		MessageInfos:      file_api_autorix_argus_v1_argus_proto_msgTypes,
	}.Build()
	File_api_autorix_argus_v1_argus_proto = out.File
	file_api_autorix_argus_v1_argus_proto_goTypes = nil
	file_api_autorix_argus_v1_argus_proto_depIdxs = nil
}
