// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: api/autorix/nexus/v1/nexus.proto

package nexusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelationTuple represents a Zanzibar tuple with optional ABAC conditions (Caveats)
type RelationTuple struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Object           string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Relation         string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	SubjectId        string                 `protobuf:"bytes,4,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectNamespace string                 `protobuf:"bytes,5,opt,name=subject_namespace,json=subjectNamespace,proto3" json:"subject_namespace,omitempty"`
	SubjectRelation  string                 `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// ABAC Condition
	CaveatName    string           `protobuf:"bytes,7,opt,name=caveat_name,json=caveatName,proto3" json:"caveat_name,omitempty"`
	CaveatContext *structpb.Struct `protobuf:"bytes,8,opt,name=caveat_context,json=caveatContext,proto3" json:"caveat_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationTuple) Reset() {
	*x = RelationTuple{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationTuple) ProtoMessage() {}

func (x *RelationTuple) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationTuple.ProtoReflect.Descriptor instead.
func (*RelationTuple) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{0}
}

func (x *RelationTuple) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *RelationTuple) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *RelationTuple) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *RelationTuple) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *RelationTuple) GetSubjectNamespace() string {
	if x != nil {
		return x.SubjectNamespace
	}
	return ""
}

func (x *RelationTuple) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *RelationTuple) GetCaveatName() string {
	if x != nil {
		return x.CaveatName
	}
	return ""
}

func (x *RelationTuple) GetCaveatContext() *structpb.Struct {
	if x != nil {
		return x.CaveatContext
	}
	return nil
}

type CaveatDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CelExpression string                 `protobuf:"bytes,2,opt,name=cel_expression,json=celExpression,proto3" json:"cel_expression,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaveatDefinition) Reset() {
	*x = CaveatDefinition{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaveatDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaveatDefinition) ProtoMessage() {}

func (x *CaveatDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaveatDefinition.ProtoReflect.Descriptor instead.
func (*CaveatDefinition) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{1}
}

func (x *CaveatDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CaveatDefinition) GetCelExpression() string {
	if x != nil {
		return x.CelExpression
	}
	return ""
}

type WriteTuplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuples        []*RelationTuple       `protobuf:"bytes,1,rep,name=tuples,proto3" json:"tuples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTuplesRequest) Reset() {
	*x = WriteTuplesRequest{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTuplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTuplesRequest) ProtoMessage() {}

func (x *WriteTuplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTuplesRequest.ProtoReflect.Descriptor instead.
func (*WriteTuplesRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{2}
}

func (x *WriteTuplesRequest) GetTuples() []*RelationTuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

type WriteTuplesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResolutionToken string                 `protobuf:"bytes,1,opt,name=resolution_token,json=resolutionToken,proto3" json:"resolution_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WriteTuplesResponse) Reset() {
	*x = WriteTuplesResponse{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTuplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTuplesResponse) ProtoMessage() {}

func (x *WriteTuplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTuplesResponse.ProtoReflect.Descriptor instead.
func (*WriteTuplesResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{3}
}

func (x *WriteTuplesResponse) GetResolutionToken() string {
	if x != nil {
		return x.ResolutionToken
	}
	return ""
}

type WriteCaveatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Caveats       []*CaveatDefinition    `protobuf:"bytes,1,rep,name=caveats,proto3" json:"caveats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCaveatsRequest) Reset() {
	*x = WriteCaveatsRequest{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCaveatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCaveatsRequest) ProtoMessage() {}

func (x *WriteCaveatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCaveatsRequest.ProtoReflect.Descriptor instead.
func (*WriteCaveatsRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{4}
}

func (x *WriteCaveatsRequest) GetCaveats() []*CaveatDefinition {
	if x != nil {
		return x.Caveats
	}
	return nil
}

type WriteCaveatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCaveatsResponse) Reset() {
	*x = WriteCaveatsResponse{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCaveatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCaveatsResponse) ProtoMessage() {}

func (x *WriteCaveatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCaveatsResponse.ProtoReflect.Descriptor instead.
func (*WriteCaveatsResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{5}
}

type DeleteTuplesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuples        []*RelationTuple       `protobuf:"bytes,1,rep,name=tuples,proto3" json:"tuples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTuplesRequest) Reset() {
	*x = DeleteTuplesRequest{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTuplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTuplesRequest) ProtoMessage() {}

func (x *DeleteTuplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTuplesRequest.ProtoReflect.Descriptor instead.
func (*DeleteTuplesRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTuplesRequest) GetTuples() []*RelationTuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

type DeleteTuplesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResolutionToken string                 `protobuf:"bytes,1,opt,name=resolution_token,json=resolutionToken,proto3" json:"resolution_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteTuplesResponse) Reset() {
	*x = DeleteTuplesResponse{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTuplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTuplesResponse) ProtoMessage() {}

func (x *DeleteTuplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTuplesResponse.ProtoReflect.Descriptor instead.
func (*DeleteTuplesResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTuplesResponse) GetResolutionToken() string {
	if x != nil {
		return x.ResolutionToken
	}
	return ""
}

type CheckRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Object           string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Relation         string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	SubjectId        string                 `protobuf:"bytes,4,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	SubjectNamespace string                 `protobuf:"bytes,5,opt,name=subject_namespace,json=subjectNamespace,proto3" json:"subject_namespace,omitempty"`
	SubjectRelation  string                 `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// Dynamic context for ABAC evaluation provided by the caller
	RequestContext  *structpb.Struct `protobuf:"bytes,7,opt,name=request_context,json=requestContext,proto3" json:"request_context,omitempty"`
	ResolutionToken string           `protobuf:"bytes,8,opt,name=resolution_token,json=resolutionToken,proto3" json:"resolution_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{8}
}

func (x *CheckRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CheckRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *CheckRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CheckRequest) GetSubjectNamespace() string {
	if x != nil {
		return x.SubjectNamespace
	}
	return ""
}

func (x *CheckRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *CheckRequest) GetRequestContext() *structpb.Struct {
	if x != nil {
		return x.RequestContext
	}
	return nil
}

func (x *CheckRequest) GetResolutionToken() string {
	if x != nil {
		return x.ResolutionToken
	}
	return ""
}

type CheckResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Allowed         bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	ResolutionToken string                 `protobuf:"bytes,2,opt,name=resolution_token,json=resolutionToken,proto3" json:"resolution_token,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // Debugging info if denied due to caveats
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{9}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetResolutionToken() string {
	if x != nil {
		return x.ResolutionToken
	}
	return ""
}

func (x *CheckResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ExpandRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Object          string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Relation        string                 `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	ResolutionToken string                 `protobuf:"bytes,4,opt,name=resolution_token,json=resolutionToken,proto3" json:"resolution_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{10}
}

func (x *ExpandRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ExpandRequest) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ExpandRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ExpandRequest) GetResolutionToken() string {
	if x != nil {
		return x.ResolutionToken
	}
	return ""
}

type ExpandResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Tree          *ExpandResponse_TreeNode `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandResponse) Reset() {
	*x = ExpandResponse{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse) ProtoMessage() {}

func (x *ExpandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandResponse.ProtoReflect.Descriptor instead.
func (*ExpandResponse) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{11}
}

func (x *ExpandResponse) GetTree() *ExpandResponse_TreeNode {
	if x != nil {
		return x.Tree
	}
	return nil
}

type ExpandResponse_TreeNode struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Type          string                     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Tuple         *RelationTuple             `protobuf:"bytes,2,opt,name=tuple,proto3" json:"tuple,omitempty"`
	Children      []*ExpandResponse_TreeNode `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandResponse_TreeNode) Reset() {
	*x = ExpandResponse_TreeNode{}
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandResponse_TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandResponse_TreeNode) ProtoMessage() {}

func (x *ExpandResponse_TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_api_autorix_nexus_v1_nexus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandResponse_TreeNode.ProtoReflect.Descriptor instead.
func (*ExpandResponse_TreeNode) Descriptor() ([]byte, []int) {
	return file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ExpandResponse_TreeNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ExpandResponse_TreeNode) GetTuple() *RelationTuple {
	if x != nil {
		return x.Tuple
	}
	return nil
}

func (x *ExpandResponse_TreeNode) GetChildren() []*ExpandResponse_TreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_api_autorix_nexus_v1_nexus_proto protoreflect.FileDescriptor

const file_api_autorix_nexus_v1_nexus_proto_rawDesc = "" +
	"\n" +
	" api/autorix/nexus/v1/nexus.proto\x12\x10autorix.nexus.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xb9\x02\n" +
	"\rRelationTuple\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x04 \x01(\tR\tsubjectId\x12+\n" +
	"\x11subject_namespace\x18\x05 \x01(\tR\x10subjectNamespace\x12)\n" +
	"\x10subject_relation\x18\x06 \x01(\tR\x0fsubjectRelation\x12\x1f\n" +
	"\vcaveat_name\x18\a \x01(\tR\n" +
	"caveatName\x12>\n" +
	"\x0ecaveat_context\x18\b \x01(\v2\x17.google.protobuf.StructR\rcaveatContext\"M\n" +
	"\x10CaveatDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0ecel_expression\x18\x02 \x01(\tR\rcelExpression\"M\n" +
	"\x12WriteTuplesRequest\x127\n" +
	"\x06tuples\x18\x01 \x03(\v2\x1f.autorix.nexus.v1.RelationTupleR\x06tuples\"@\n" +
	"\x13WriteTuplesResponse\x12)\n" +
	"\x10resolution_token\x18\x01 \x01(\tR\x0fresolutionToken\"S\n" +
	"\x13WriteCaveatsRequest\x12<\n" +
	"\acaveats\x18\x01 \x03(\v2\".autorix.nexus.v1.CaveatDefinitionR\acaveats\"\x16\n" +
	"\x14WriteCaveatsResponse\"N\n" +
	"\x13DeleteTuplesRequest\x127\n" +
	"\x06tuples\x18\x01 \x03(\v2\x1f.autorix.nexus.v1.RelationTupleR\x06tuples\"A\n" +
	"\x14DeleteTuplesResponse\x12)\n" +
	"\x10resolution_token\x18\x01 \x01(\tR\x0fresolutionToken\"\xc4\x02\n" +
	"\fCheckRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x04 \x01(\tR\tsubjectId\x12+\n" +
	"\x11subject_namespace\x18\x05 \x01(\tR\x10subjectNamespace\x12)\n" +
	"\x10subject_relation\x18\x06 \x01(\tR\x0fsubjectRelation\x12@\n" +
	"\x0frequest_context\x18\a \x01(\v2\x17.google.protobuf.StructR\x0erequestContext\x12)\n" +
	"\x10resolution_token\x18\b \x01(\tR\x0fresolutionToken\"l\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12)\n" +
	"\x10resolution_token\x18\x02 \x01(\tR\x0fresolutionToken\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x8c\x01\n" +
	"\rExpandRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x1a\n" +
	"\brelation\x18\x03 \x01(\tR\brelation\x12)\n" +
	"\x10resolution_token\x18\x04 \x01(\tR\x0fresolutionToken\"\xee\x01\n" +
	"\x0eExpandResponse\x12=\n" +
	"\x04tree\x18\x01 \x01(\v2).autorix.nexus.v1.ExpandResponse.TreeNodeR\x04tree\x1a\x9c\x01\n" +
	"\bTreeNode\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x125\n" +
	"\x05tuple\x18\x02 \x01(\v2\x1f.autorix.nexus.v1.RelationTupleR\x05tuple\x12E\n" +
	"\bchildren\x18\x03 \x03(\v2).autorix.nexus.v1.ExpandResponse.TreeNodeR\bchildren2\xbf\x03\n" +
	"\fNexusService\x12Z\n" +
	"\vWriteTuples\x12$.autorix.nexus.v1.WriteTuplesRequest\x1a%.autorix.nexus.v1.WriteTuplesResponse\x12]\n" +
	"\fDeleteTuples\x12%.autorix.nexus.v1.DeleteTuplesRequest\x1a&.autorix.nexus.v1.DeleteTuplesResponse\x12]\n" +
	"\fWriteCaveats\x12%.autorix.nexus.v1.WriteCaveatsRequest\x1a&.autorix.nexus.v1.WriteCaveatsResponse\x12H\n" +
	"\x05Check\x12\x1e.autorix.nexus.v1.CheckRequest\x1a\x1f.autorix.nexus.v1.CheckResponse\x12K\n" +
	"\x06Expand\x12\x1f.autorix.nexus.v1.ExpandRequest\x1a .autorix.nexus.v1.ExpandResponseB7Z5github.com/autorix/nexus/api/autorix/nexus/v1;nexusv1b\x06proto3"

var (
	file_api_autorix_nexus_v1_nexus_proto_rawDescOnce sync.Once
	file_api_autorix_nexus_v1_nexus_proto_rawDescData []byte
)

func file_api_autorix_nexus_v1_nexus_proto_rawDescGZIP() []byte {
	file_api_autorix_nexus_v1_nexus_proto_rawDescOnce.Do(func() {
		file_api_autorix_nexus_v1_nexus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_autorix_nexus_v1_nexus_proto_rawDesc), len(file_api_autorix_nexus_v1_nexus_proto_rawDesc)))
	})
	return file_api_autorix_nexus_v1_nexus_proto_rawDescData
}

var file_api_autorix_nexus_v1_nexus_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_autorix_nexus_v1_nexus_proto_goTypes = []any{
	(*RelationTuple)(nil),           // 0: autorix.nexus.v1.RelationTuple
	(*CaveatDefinition)(nil),        // 1: autorix.nexus.v1.CaveatDefinition
	(*WriteTuplesRequest)(nil),      // 2: autorix.nexus.v1.WriteTuplesRequest
	(*WriteTuplesResponse)(nil),     // 3: autorix.nexus.v1.WriteTuplesResponse
	(*WriteCaveatsRequest)(nil),     // 4: autorix.nexus.v1.WriteCaveatsRequest
	(*WriteCaveatsResponse)(nil),    // 5: autorix.nexus.v1.WriteCaveatsResponse
	(*DeleteTuplesRequest)(nil),     // 6: autorix.nexus.v1.DeleteTuplesRequest
	(*DeleteTuplesResponse)(nil),    // 7: autorix.nexus.v1.DeleteTuplesResponse
	(*CheckRequest)(nil),            // 8: autorix.nexus.v1.CheckRequest
	(*CheckResponse)(nil),           // 9: autorix.nexus.v1.CheckResponse
	(*ExpandRequest)(nil),           // 10: autorix.nexus.v1.ExpandRequest
	(*ExpandResponse)(nil),          // 11: autorix.nexus.v1.ExpandResponse
	(*ExpandResponse_TreeNode)(nil), // 12: autorix.nexus.v1.ExpandResponse.TreeNode
	(*structpb.Struct)(nil),         // 13: google.protobuf.Struct
}
var file_api_autorix_nexus_v1_nexus_proto_depIdxs = []int32{
	13, // 0: autorix.nexus.v1.RelationTuple.caveat_context:type_name -> google.protobuf.Struct
	0,  // 1: autorix.nexus.v1.WriteTuplesRequest.tuples:type_name -> autorix.nexus.v1.RelationTuple
	1,  // 2: autorix.nexus.v1.WriteCaveatsRequest.caveats:type_name -> autorix.nexus.v1.CaveatDefinition
	0,  // 3: autorix.nexus.v1.DeleteTuplesRequest.tuples:type_name -> autorix.nexus.v1.RelationTuple
	13, // 4: autorix.nexus.v1.CheckRequest.request_context:type_name -> google.protobuf.Struct
	12, // 5: autorix.nexus.v1.ExpandResponse.tree:type_name -> autorix.nexus.v1.ExpandResponse.TreeNode
	0,  // 6: autorix.nexus.v1.ExpandResponse.TreeNode.tuple:type_name -> autorix.nexus.v1.RelationTuple
	12, // 7: autorix.nexus.v1.ExpandResponse.TreeNode.children:type_name -> autorix.nexus.v1.ExpandResponse.TreeNode
	2,  // 8: autorix.nexus.v1.NexusService.WriteTuples:input_type -> autorix.nexus.v1.WriteTuplesRequest
	6,  // 9: autorix.nexus.v1.NexusService.DeleteTuples:input_type -> autorix.nexus.v1.DeleteTuplesRequest
	4,  // 10: autorix.nexus.v1.NexusService.WriteCaveats:input_type -> autorix.nexus.v1.WriteCaveatsRequest
	8,  // 11: autorix.nexus.v1.NexusService.Check:input_type -> autorix.nexus.v1.CheckRequest
	10, // 12: autorix.nexus.v1.NexusService.Expand:input_type -> autorix.nexus.v1.ExpandRequest
	3,  // 13: autorix.nexus.v1.NexusService.WriteTuples:output_type -> autorix.nexus.v1.WriteTuplesResponse
	7,  // 14: autorix.nexus.v1.NexusService.DeleteTuples:output_type -> autorix.nexus.v1.DeleteTuplesResponse
	5,  // 15: autorix.nexus.v1.NexusService.WriteCaveats:output_type -> autorix.nexus.v1.WriteCaveatsResponse
	9,  // 16: autorix.nexus.v1.NexusService.Check:output_type -> autorix.nexus.v1.CheckResponse
	11, // 17: autorix.nexus.v1.NexusService.Expand:output_type -> autorix.nexus.v1.ExpandResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_autorix_nexus_v1_nexus_proto_init() }
func file_api_autorix_nexus_v1_nexus_proto_init() {
	if File_api_autorix_nexus_v1_nexus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_autorix_nexus_v1_nexus_proto_rawDesc), len(file_api_autorix_nexus_v1_nexus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_autorix_nexus_v1_nexus_proto_goTypes,
		DependencyIndexes: file_api_autorix_nexus_v1_nexus_proto_depIdxs,
		MessageInfos:      file_api_autorix_nexus_v1_nexus_proto_msgTypes,
	}.Build()
	File_api_autorix_nexus_v1_nexus_proto = out.File
	file_api_autorix_nexus_v1_nexus_proto_goTypes = nil
	file_api_autorix_nexus_v1_nexus_proto_depIdxs = nil
}
