package postgres

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/autorix/themis/internal/core"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Repository implements core.PolicyRepository backed by PostgreSQL.
type Repository struct {
	pool *pgxpool.Pool
}

// NewRepository creates a new PostgreSQL-backed policy repository.
func NewRepository(pool *pgxpool.Pool) *Repository {
	return &Repository{pool: pool}
}

// Create inserts a new policy. The ID is generated by the database (gen_random_uuid).
func (r *Repository) Create(ctx context.Context, policy *core.Policy) error {
	labelsJSON, err := json.Marshal(policy.Labels)
	if err != nil {
		return fmt.Errorf("failed to marshal labels: %w", err)
	}

	err = r.pool.QueryRow(ctx, `
		INSERT INTO policies (tenant_id, name, description, expression, priority, enabled, labels)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING id, created_at, updated_at
	`, policy.TenantID, policy.Name, policy.Description,
		policy.Expression, policy.Priority, policy.Enabled, labelsJSON,
	).Scan(&policy.ID, &policy.CreatedAt, &policy.UpdatedAt)

	if err != nil {
		return fmt.Errorf("failed to insert policy: %w", err)
	}

	return nil
}

// GetByID retrieves a single policy by tenant and ID.
func (r *Repository) GetByID(ctx context.Context, tenantID, policyID string) (*core.Policy, error) {
	var p core.Policy
	var labelsJSON []byte

	err := r.pool.QueryRow(ctx, `
		SELECT id, tenant_id, name, description, expression, priority, enabled, labels, created_at, updated_at
		FROM policies
		WHERE tenant_id = $1 AND id = $2
	`, tenantID, policyID).Scan(
		&p.ID, &p.TenantID, &p.Name, &p.Description, &p.Expression,
		&p.Priority, &p.Enabled, &labelsJSON, &p.CreatedAt, &p.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("policy not found: %w", err)
	}

	if labelsJSON != nil {
		if err := json.Unmarshal(labelsJSON, &p.Labels); err != nil {
			return nil, fmt.Errorf("failed to unmarshal labels: %w", err)
		}
	}

	return &p, nil
}

// List returns policies matching the given filter.
func (r *Repository) List(ctx context.Context, filter core.ListFilter) ([]core.Policy, error) {
	query := `
		SELECT id, tenant_id, name, description, expression, priority, enabled, labels, created_at, updated_at
		FROM policies
		WHERE tenant_id = $1
	`
	args := []interface{}{filter.TenantID}
	argIdx := 2

	if filter.EnabledOnly {
		query += fmt.Sprintf(" AND enabled = $%d", argIdx)
		args = append(args, true)
		argIdx++
	}

	// Label filtering: each label must match (AND semantics)
	for k, v := range filter.Labels {
		query += fmt.Sprintf(" AND labels->>'%s' = $%d", sanitizeKey(k), argIdx)
		args = append(args, v)
		argIdx++
	}

	query += " ORDER BY priority ASC, created_at ASC"

	rows, err := r.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to query policies: %w", err)
	}
	defer rows.Close()

	var policies []core.Policy
	for rows.Next() {
		var p core.Policy
		var labelsJSON []byte

		if err := rows.Scan(
			&p.ID, &p.TenantID, &p.Name, &p.Description, &p.Expression,
			&p.Priority, &p.Enabled, &labelsJSON, &p.CreatedAt, &p.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan policy: %w", err)
		}

		if labelsJSON != nil {
			if err := json.Unmarshal(labelsJSON, &p.Labels); err != nil {
				return nil, fmt.Errorf("failed to unmarshal labels: %w", err)
			}
		}

		policies = append(policies, p)
	}

	return policies, nil
}

// Update modifies an existing policy.
func (r *Repository) Update(ctx context.Context, policy *core.Policy) error {
	labelsJSON, err := json.Marshal(policy.Labels)
	if err != nil {
		return fmt.Errorf("failed to marshal labels: %w", err)
	}

	tag, err := r.pool.Exec(ctx, `
		UPDATE policies
		SET name = $3, description = $4, expression = $5, priority = $6,
		    enabled = $7, labels = $8, updated_at = NOW()
		WHERE tenant_id = $1 AND id = $2
	`, policy.TenantID, policy.ID, policy.Name, policy.Description,
		policy.Expression, policy.Priority, policy.Enabled, labelsJSON,
	)
	if err != nil {
		return fmt.Errorf("failed to update policy: %w", err)
	}

	if tag.RowsAffected() == 0 {
		return fmt.Errorf("policy not found")
	}

	return nil
}

// Delete removes a policy by tenant and ID.
func (r *Repository) Delete(ctx context.Context, tenantID, policyID string) error {
	tag, err := r.pool.Exec(ctx, `
		DELETE FROM policies WHERE tenant_id = $1 AND id = $2
	`, tenantID, policyID)
	if err != nil {
		return fmt.Errorf("failed to delete policy: %w", err)
	}

	if tag.RowsAffected() == 0 {
		return fmt.Errorf("policy not found")
	}

	return nil
}

// sanitizeKey prevents SQL injection in JSONB key access.
// Only allows alphanumeric characters and underscores.
func sanitizeKey(key string) string {
	var b strings.Builder
	for _, r := range key {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		}
	}
	return b.String()
}
