package postgres

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/autorix/platform/paging"
	"github.com/autorix/themis/internal/core"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Repository implements core.PolicyRepository backed by PostgreSQL.
type Repository struct {
	pool *pgxpool.Pool
}

// NewRepository creates a new PostgreSQL-backed policy repository.
func NewRepository(pool *pgxpool.Pool) *Repository {
	return &Repository{pool: pool}
}

// Pool exposes the underlying connection pool so main.go can wire
// postgres.Check into the engine's health.Checker (ADR 0001).
func (r *Repository) Pool() *pgxpool.Pool {
	return r.pool
}

// Create inserts a new policy. The ID is generated by the database (gen_random_uuid).
func (r *Repository) Create(ctx context.Context, policy *core.Policy) error {
	labelsJSON, err := json.Marshal(policy.Labels)
	if err != nil {
		return fmt.Errorf("failed to marshal labels: %w", err)
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	err = tx.QueryRow(ctx, `
		INSERT INTO policies (tenant_id, name, description, expression, priority, enabled, labels)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		RETURNING id, created_at, updated_at
	`, policy.TenantID, policy.Name, policy.Description,
		policy.Expression, policy.Priority, policy.Enabled, labelsJSON,
	).Scan(&policy.ID, &policy.CreatedAt, &policy.UpdatedAt)
	if err != nil {
		return fmt.Errorf("failed to insert policy: %w", err)
	}

	// Record initial version (version 1)
	_, err = tx.Exec(ctx, `
		INSERT INTO policy_versions (policy_id, tenant_id, version, name, description, expression, priority, enabled, labels, created_at)
		VALUES ($1, $2, 1, $3, $4, $5, $6, $7, $8, $9)
	`, policy.ID, policy.TenantID, policy.Name, policy.Description,
		policy.Expression, policy.Priority, policy.Enabled, labelsJSON, policy.CreatedAt)
	if err != nil {
		return fmt.Errorf("failed to insert initial policy version: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("failed to commit tx: %w", err)
	}

	return nil
}

// GetByID retrieves a single policy by tenant and ID.
func (r *Repository) GetByID(ctx context.Context, tenantID, policyID string) (*core.Policy, error) {
	var p core.Policy
	var labelsJSON []byte

	err := r.pool.QueryRow(ctx, `
		SELECT id, tenant_id, name, description, expression, priority, enabled, labels, created_at, updated_at
		FROM policies
		WHERE tenant_id = $1 AND id = $2
	`, tenantID, policyID).Scan(
		&p.ID, &p.TenantID, &p.Name, &p.Description, &p.Expression,
		&p.Priority, &p.Enabled, &labelsJSON, &p.CreatedAt, &p.UpdatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("policy not found: %w", err)
	}

	if labelsJSON != nil {
		if err := json.Unmarshal(labelsJSON, &p.Labels); err != nil {
			return nil, fmt.Errorf("failed to unmarshal labels: %w", err)
		}
	}

	return &p, nil
}

// List returns policies matching the given filter.
func (r *Repository) List(ctx context.Context, filter core.ListFilter) ([]core.Policy, error) {
	query := `
		SELECT id, tenant_id, name, description, expression, priority, enabled, labels, created_at, updated_at
		FROM policies
		WHERE tenant_id = $1
	`
	args := []interface{}{filter.TenantID}
	argIdx := 2

	if filter.EnabledOnly {
		query += fmt.Sprintf(" AND enabled = $%d", argIdx)
		args = append(args, true)
		argIdx++
	}

	// Label filtering: each label must match (AND semantics)
	for k, v := range filter.Labels {
		query += fmt.Sprintf(" AND labels->>'%s' = $%d", sanitizeKey(k), argIdx)
		args = append(args, v)
		argIdx++
	}

	query += " ORDER BY priority ASC, created_at ASC"

	rows, err := r.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to query policies: %w", err)
	}
	defer rows.Close()

	var policies []core.Policy
	for rows.Next() {
		var p core.Policy
		var labelsJSON []byte

		if err := rows.Scan(
			&p.ID, &p.TenantID, &p.Name, &p.Description, &p.Expression,
			&p.Priority, &p.Enabled, &labelsJSON, &p.CreatedAt, &p.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan policy: %w", err)
		}

		if labelsJSON != nil {
			if err := json.Unmarshal(labelsJSON, &p.Labels); err != nil {
				return nil, fmt.Errorf("failed to unmarshal labels: %w", err)
			}
		}

		policies = append(policies, p)
	}

	return policies, nil
}

// policyCursor is the "priority|createdAt|id" payload wrapped by
// paging.EncodeCursor for ListPage. It mirrors List's ordering (priority
// ASC, created_at ASC) plus id as a final tie-break for full determinism.
func decodePolicyCursor(cursor string) (priority int32, createdAt time.Time, id string, err error) {
	decoded, decErr := paging.DecodeCursor(cursor)
	if decErr != nil {
		return 0, time.Time{}, "", decErr
	}
	parts := strings.SplitN(decoded, "|", 3)
	if len(parts) != 3 {
		return 0, time.Time{}, "", errors.New("malformed cursor payload")
	}
	p, convErr := strconv.ParseInt(parts[0], 10, 32)
	if convErr != nil {
		return 0, time.Time{}, "", fmt.Errorf("invalid cursor priority: %w", convErr)
	}
	ts, tsErr := time.Parse(time.RFC3339Nano, parts[1])
	if tsErr != nil {
		return 0, time.Time{}, "", fmt.Errorf("invalid cursor timestamp: %w", tsErr)
	}
	return int32(p), ts, parts[2], nil
}

// ListPage is List's paginated counterpart for the admin listing endpoint:
// it applies the same tenant/enabled/label filters, but returns at most
// limit+1 rows to detect whether more exist beyond the page, and a
// non-empty cursor restricts the query to rows strictly after the last one
// returned by a previous call. List itself is left untouched because
// Service.Evaluate needs the complete filtered set to run bulk policy
// evaluation, not a page of it.
func (r *Repository) ListPage(ctx context.Context, filter core.ListFilter, limit int, cursor string) ([]core.Policy, bool, error) {
	query := `
		SELECT id, tenant_id, name, description, expression, priority, enabled, labels, created_at, updated_at
		FROM policies
		WHERE tenant_id = $1
	`
	args := []interface{}{filter.TenantID}
	argIdx := 2

	if filter.EnabledOnly {
		query += fmt.Sprintf(" AND enabled = $%d", argIdx)
		args = append(args, true)
		argIdx++
	}

	for k, v := range filter.Labels {
		query += fmt.Sprintf(" AND labels->>'%s' = $%d", sanitizeKey(k), argIdx)
		args = append(args, v)
		argIdx++
	}

	if cursor != "" {
		priority, createdAt, id, err := decodePolicyCursor(cursor)
		if err != nil {
			return nil, false, fmt.Errorf("invalid cursor: %w", err)
		}
		query += fmt.Sprintf(" AND (priority, created_at, id) > ($%d, $%d, $%d)", argIdx, argIdx+1, argIdx+2)
		args = append(args, priority, createdAt, id)
		argIdx += 3
	}

	query += fmt.Sprintf(" ORDER BY priority ASC, created_at ASC, id ASC LIMIT $%d", argIdx)
	args = append(args, limit+1)

	rows, err := r.pool.Query(ctx, query, args...)
	if err != nil {
		return nil, false, fmt.Errorf("failed to query policies: %w", err)
	}
	defer rows.Close()

	var policies []core.Policy
	for rows.Next() {
		var p core.Policy
		var labelsJSON []byte

		if err := rows.Scan(
			&p.ID, &p.TenantID, &p.Name, &p.Description, &p.Expression,
			&p.Priority, &p.Enabled, &labelsJSON, &p.CreatedAt, &p.UpdatedAt,
		); err != nil {
			return nil, false, fmt.Errorf("failed to scan policy: %w", err)
		}

		if labelsJSON != nil {
			if err := json.Unmarshal(labelsJSON, &p.Labels); err != nil {
				return nil, false, fmt.Errorf("failed to unmarshal labels: %w", err)
			}
		}

		policies = append(policies, p)
	}

	hasMore := len(policies) > limit
	if hasMore {
		policies = policies[:limit]
	}
	return policies, hasMore, nil
}

// Update modifies an existing policy and adds a new revision to policy_versions.
func (r *Repository) Update(ctx context.Context, policy *core.Policy) error {
	labelsJSON, err := json.Marshal(policy.Labels)
	if err != nil {
		return fmt.Errorf("failed to marshal labels: %w", err)
	}

	tx, err := r.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin tx: %w", err)
	}
	defer tx.Rollback(ctx)

	tag, err := tx.Exec(ctx, `
		UPDATE policies
		SET name = $3, description = $4, expression = $5, priority = $6,
		    enabled = $7, labels = $8, updated_at = NOW()
		WHERE tenant_id = $1 AND id = $2
	`, policy.TenantID, policy.ID, policy.Name, policy.Description,
		policy.Expression, policy.Priority, policy.Enabled, labelsJSON,
	)
	if err != nil {
		return fmt.Errorf("failed to update policy: %w", err)
	}

	if tag.RowsAffected() == 0 {
		return fmt.Errorf("policy not found")
	}

	var nextVersion int32
	err = tx.QueryRow(ctx, `
		SELECT COALESCE(MAX(version), 0) + 1
		FROM policy_versions
		WHERE tenant_id = $1 AND policy_id = $2
	`, policy.TenantID, policy.ID).Scan(&nextVersion)
	if err != nil {
		return fmt.Errorf("failed to compute next version: %w", err)
	}

	_, err = tx.Exec(ctx, `
		INSERT INTO policy_versions (policy_id, tenant_id, version, name, description, expression, priority, enabled, labels, created_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
	`, policy.ID, policy.TenantID, nextVersion, policy.Name, policy.Description,
		policy.Expression, policy.Priority, policy.Enabled, labelsJSON)
	if err != nil {
		return fmt.Errorf("failed to insert policy version: %w", err)
	}

	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("failed to commit tx: %w", err)
	}

	return nil
}

// Delete removes a policy by tenant and ID.
func (r *Repository) Delete(ctx context.Context, tenantID, policyID string) error {
	tag, err := r.pool.Exec(ctx, `
		DELETE FROM policies WHERE tenant_id = $1 AND id = $2
	`, tenantID, policyID)
	if err != nil {
		return fmt.Errorf("failed to delete policy: %w", err)
	}

	if tag.RowsAffected() == 0 {
		return fmt.Errorf("policy not found")
	}

	return nil
}

// ListVersions returns all historical snapshots for a policy ordered newest first.
func (r *Repository) ListVersions(ctx context.Context, tenantID, policyID string) ([]core.PolicyVersion, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT id, policy_id, tenant_id, version, name, description, expression, priority, enabled, labels, created_at
		FROM policy_versions
		WHERE tenant_id = $1 AND policy_id = $2
		ORDER BY version DESC
	`, tenantID, policyID)
	if err != nil {
		return nil, fmt.Errorf("failed to query policy versions: %w", err)
	}
	defer rows.Close()

	var versions []core.PolicyVersion
	for rows.Next() {
		var v core.PolicyVersion
		var labelsJSON []byte
		if err := rows.Scan(
			&v.ID, &v.PolicyID, &v.TenantID, &v.Version, &v.Name,
			&v.Description, &v.Expression, &v.Priority, &v.Enabled,
			&labelsJSON, &v.CreatedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan policy version: %w", err)
		}
		if labelsJSON != nil {
			if err := json.Unmarshal(labelsJSON, &v.Labels); err != nil {
				return nil, fmt.Errorf("failed to unmarshal labels: %w", err)
			}
		}
		versions = append(versions, v)
	}

	return versions, nil
}

// GetVersion retrieves a single historical snapshot of a policy.
func (r *Repository) GetVersion(ctx context.Context, tenantID, policyID string, version int32) (*core.PolicyVersion, error) {
	var v core.PolicyVersion
	var labelsJSON []byte
	err := r.pool.QueryRow(ctx, `
		SELECT id, policy_id, tenant_id, version, name, description, expression, priority, enabled, labels, created_at
		FROM policy_versions
		WHERE tenant_id = $1 AND policy_id = $2 AND version = $3
	`, tenantID, policyID, version).Scan(
		&v.ID, &v.PolicyID, &v.TenantID, &v.Version, &v.Name,
		&v.Description, &v.Expression, &v.Priority, &v.Enabled,
		&labelsJSON, &v.CreatedAt,
	)
	if err != nil {
		return nil, fmt.Errorf("policy version not found: %w", err)
	}
	if labelsJSON != nil {
		if err := json.Unmarshal(labelsJSON, &v.Labels); err != nil {
			return nil, fmt.Errorf("failed to unmarshal labels: %w", err)
		}
	}
	return &v, nil
}

// Rollback restores a policy's state to a previous version and creates a new revision record.
func (r *Repository) Rollback(ctx context.Context, tenantID, policyID string, version int32) (*core.Policy, error) {
	v, err := r.GetVersion(ctx, tenantID, policyID, version)
	if err != nil {
		return nil, err
	}

	p := &core.Policy{
		ID:          v.PolicyID,
		TenantID:    v.TenantID,
		Name:        v.Name,
		Description: v.Description,
		Expression:  v.Expression,
		Priority:    v.Priority,
		Enabled:     v.Enabled,
		Labels:      v.Labels,
	}

	if err := r.Update(ctx, p); err != nil {
		return nil, fmt.Errorf("failed to apply rollback: %w", err)
	}

	return r.GetByID(ctx, tenantID, policyID)
}

// CreateFixture inserts a new test fixture attached to a policy.
func (r *Repository) CreateFixture(ctx context.Context, fixture *core.PolicyFixture) error {
	payloadJSON, err := json.Marshal(fixture.Payload)
	if err != nil {
		return fmt.Errorf("failed to marshal payload: %w", err)
	}

	err = r.pool.QueryRow(ctx, `
		INSERT INTO policy_fixtures (policy_id, tenant_id, name, description, payload, expected_result)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id, created_at, updated_at
	`, fixture.PolicyID, fixture.TenantID, fixture.Name, fixture.Description, payloadJSON, fixture.ExpectedResult,
	).Scan(&fixture.ID, &fixture.CreatedAt, &fixture.UpdatedAt)
	if err != nil {
		return fmt.Errorf("failed to insert policy fixture: %w", err)
	}
	return nil
}

// ListFixtures retrieves all test fixtures attached to a policy.
func (r *Repository) ListFixtures(ctx context.Context, tenantID, policyID string) ([]core.PolicyFixture, error) {
	rows, err := r.pool.Query(ctx, `
		SELECT id, policy_id, tenant_id, name, description, payload, expected_result, created_at, updated_at
		FROM policy_fixtures
		WHERE tenant_id = $1 AND policy_id = $2
		ORDER BY created_at ASC
	`, tenantID, policyID)
	if err != nil {
		return nil, fmt.Errorf("failed to query policy fixtures: %w", err)
	}
	defer rows.Close()

	var fixtures []core.PolicyFixture
	for rows.Next() {
		var f core.PolicyFixture
		var payloadJSON []byte
		if err := rows.Scan(
			&f.ID, &f.PolicyID, &f.TenantID, &f.Name, &f.Description,
			&payloadJSON, &f.ExpectedResult, &f.CreatedAt, &f.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("failed to scan policy fixture: %w", err)
		}
		if payloadJSON != nil {
			if err := json.Unmarshal(payloadJSON, &f.Payload); err != nil {
				return nil, fmt.Errorf("failed to unmarshal payload: %w", err)
			}
		}
		fixtures = append(fixtures, f)
	}
	return fixtures, nil
}

// DeleteFixture removes a test fixture.
func (r *Repository) DeleteFixture(ctx context.Context, tenantID, policyID, fixtureID string) error {
	tag, err := r.pool.Exec(ctx, `
		DELETE FROM policy_fixtures
		WHERE tenant_id = $1 AND policy_id = $2 AND id = $3
	`, tenantID, policyID, fixtureID)
	if err != nil {
		return fmt.Errorf("failed to delete policy fixture: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return fmt.Errorf("policy fixture not found")
	}
	return nil
}

// sanitizeKey prevents SQL injection in JSONB key access.
// Only allows alphanumeric characters and underscores.
func sanitizeKey(key string) string {
	var b strings.Builder
	for _, r := range key {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		}
	}
	return b.String()
}
