export const SERVICES_CONFIG = {
  nexus: {
    name: "Autorix Nexus",
    role: "ReBAC + ABAC Zanzibar Engine",
    port: 50051,
    protocol: "gRPC",
    url: process.env.NEXT_PUBLIC_NEXUS_URL || "http://localhost:50051",
  },
  ego: {
    name: "Autorix Ego",
    role: "Identity & User Lifecycle (Argon2id)",
    port: 4433,
    protocol: "REST",
    url: process.env.NEXT_PUBLIC_EGO_URL || "http://localhost:4433",
  },
  janus: {
    name: "Autorix Janus",
    role: "OAuth2 & OIDC Server (JWKS/PKCE)",
    port: 4444,
    protocol: "REST/OIDC",
    url: process.env.NEXT_PUBLIC_JANUS_URL || "http://localhost:4444",
  },
  aegis: {
    name: "Autorix Aegis",
    role: "Zero Trust Identity & Access Proxy",
    port: 4455,
    protocol: "HTTP Proxy",
    url: process.env.NEXT_PUBLIC_AEGIS_URL || "http://localhost:4455",
  },
  vulcan: {
    name: "Autorix Vulcan",
    role: "API Keys & Macaroons Manager",
    port: 4466,
    protocol: "REST",
    url: process.env.NEXT_PUBLIC_VULCAN_URL || "http://localhost:4466",
  },
  hermes: {
    name: "Autorix Hermes",
    role: "Enterprise SAML 2.0 & SCIM 2.0",
    port: 4477,
    protocol: "REST/XML",
    url: process.env.NEXT_PUBLIC_HERMES_URL || "http://localhost:4477",
  },
  themis: {
    name: "Autorix Themis",
    role: "ABAC Policy & Google CEL Rules Engine",
    port: 4488,
    protocol: "REST/gRPC",
    url: process.env.NEXT_PUBLIC_THEMIS_URL || "http://localhost:4488",
  },
};
