CREATE TABLE IF NOT EXISTS namespace_schemas (
    name VARCHAR(128) PRIMARY KEY,
    schema JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
